### ISSUE TITLE
haskell-gtd-nl-server: /proc/meminfo: openFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by anka-213** [kr3v/haskell-gtd-nl#1]
On MacOS the file `/proc/meminfo` doesn't exist, so the server immediately crashes when looking for it.

**Comment by kr3v** [comment]
Thanks for the issue.

I believe I fixed this problem.

I've also changed a default extension directory (where it stores logs and `cabal get`ted repos) to `home </> "Library" </> "Application Support" </> "Code" </> "haskell-gtd-nl"`. The resulting version seemed to work on Intel Mac (not sure about the OS version though).

Could you please try building / starting the server again? Just `git pull` on the `master` branch plus `cabal install --overwrite-policy=always`.
Also, if you were to try the extension in VS Code, please use the updated version - [haskell-gtd-nl-0.3.3.vsix.zip](https://github.com/kr3v/haskell-gtd-nl/files/12752115/haskell-gtd-nl-0.3.3.vsix.zip) (unpack it plus `Extensions: Install from VSIX` VS Code command).

**Comment by kr3v** [comment]
Shoudl be fixed with 0.0.3.4
